version: '3'

services:
  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "wycs_rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
    volumes:
      - ./volumes/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - net-local

networks:
  net-local:
    driver: bridge