version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:  # Nacos环境变量的文档: https://github.com/nacos-group/nacos-docker/blob/master/README_ZH.md
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      # 开启权限校验系统
      - NACOS_AUTH_ENABLE=true
      # token 失效时间
      - NACOS_AUTH_TOKEN_EXPIRE_SECONDS=18000
      # token
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      # 权限缓存开关 ,开启后权限缓存的更新默认有15秒的延迟
      - NACOS_AUTH_CACHE_ENABLE=false
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    volumes:
      - ./volumes/nacos/logs/:/home/nacos/logs
      - ./volumes/nacos/data/:/home/nacos/data
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - net-local

networks:
  net-local:
    driver: bridge