version: '3.1'
services:
  casdoor:
    restart: always
    image: casbin/casdoor:latest
    ports:
      - "18000:18000"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
      driverName: mysql
      dataSourceName: "root:123456@tcp(db:3306)/"
    volumes:
      - ./volumes/conf:/conf/
    networks:
      - net-local
  db:
    restart: always
    image: mysql:8
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: casdoor
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./volumes/data/mysql/:/var/lib/mysql
    networks:
      - net-local
networks:
  net-local:
    driver: bridge