version: '2'
services:
  #Service for nameserver
  namesrv:
    image: apache/rocketmq:5.1.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./volumes/rocketmq/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker
  broker:
    image: apache/rocketmq:5.1.0
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./volumes/rocketmq/broker/logs:/home/rocketmq/logs
      - ./volumes/rocketmq/broker/store:/home/rocketmq/store
      - ./volumes/rocketmq/broker/conf/broker.conf:/opt/rocketmq-5.1.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-5.1.0/conf/broker.conf

  #Service for another broker -- broker1
  broker1:
    image: apache/rocketmq:5.1.0
    container_name: rmqbroker-b
    links:
      - namesrv
    ports:
      - 10929:10909
      - 10931:10911
      - 10932:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./volumes/rocketmq_broker1/broker/logs:/home/rocketmq/logs
      - ./volumes/rocketmq_broker1/broker/store:/home/rocketmq/store
      - ./volumes/rocketmq_broker1/broker/conf/broker.conf:/opt/rocketmq-5.1.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-5.1.0/conf/broker.conf
