    version: "3"
    services:
      confluence:
        image: atlassian/confluence
        container_name: confluence
        restart: always
        ports:
          - 8090:8090
          - 8091:8091
        volumes:
          - ./volumes/confluence-data:/var/atlassian/application-data/confluence
      mysql:
        image: mysql:8.0.22
        container_name: mysql
        security_opt:
          - seccomp:unconfined
        ports:
          - 6101:3306
        restart: always
        volumes:
          - ./volumes/mysql-data:/var/lib/mysql
          - ./volumes/my.cnf:/etc/mysql/my.cnf
        environment:
          - MYSQL_ROOT_PASSWORD=Kaiyuan@2020
          - TZ=Asia/Shanghai
      jira:
        image: atlassian/jira-software
        container_name: jira
        restart: always
        ports:
          - 8080:8080
        volumes:
          - ./volumes/jira-data:/var/atlassian/application-data/jira